config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :plans do
    resources :plan_recipes, only: [:index, :show]

    member do
      patch :update_positions
    end
  end

  resources :plan_recipes, only: :update
  resources :recipes, only: :create
  resources :shopping_lists, only: [:create, :update, :edit]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # get "surveys", to: "surveys#new"
  # get "surveys", to: "surveys#create"
  # get "up" => "rails/health#show", as: :rails_health_check

  get "/plans/:id/calendar", to: "plans#edit_calendar", as: :calendar
  get "/plans/:id/recipes", to: "plan_recipes#show_recipes", as: :show_recipes
  get "plans/:id/recipes/edit", to: "plans#edit", as: :edit_recipe
  post "plans/:id/recipes/update", to: "plan_recipes#update", as: :update_recipe
  get "/plans/:id/shopping-list", to: "plans#show_shopping_list", as: :show_shopping_list
  # get "plans/:id/shopping-list/edit/:id", to: "shopping_lists#edit", as: :edit_shopping_list

  # Defines the root path route ("/")
  # root "posts#index"

  # resources :surveys, only: [] do
  #   collection do
  #     get :step_one
  #     match :step_two, via: [:get, :post]
  #     match :step_three, via: [:get, :post]
  #     match :step_four, via: [:get, :post]
  #     post :submit_survey
  #   end
  # end

  resources :surveys
end
       # get 'step/:step', to: 'surveys#step', as: :survey_step
       # post 'submit', to: 'surveys#submit_survey', as: :submit_survey
   # end
 # end
# end

app/models/plan_recipe.rb
class PlanRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :plan

  validates :recipe_id, :plan_id, presence: true
  default_scope { order(:position) }
end

app/controllers/plan_recipes_controller.rb
class PlanRecipesController < ApplicationController
  def index
    @plan = Plan.find(params[:plan_id])
    @plan_recipes = @plan.plan_recipes
    @plan_recipe = @plan_recipes.first
    @shopping_list = ShoppingList.where(plan: @plan).includes(:ingredient).order('ingredients.name')
  end

  def show
    @plan = Plan.find(params[:plan_id])
    @plan_recipe = @plan.plan_recipes.find(params[:id])
    @shopping_list = ShoppingList.where(plan: @plan).includes(:ingredient).order('ingredients.name')
  end

  def new
    @plan = Plan.find(params[:plan_id])
    @plan.plan_recipes
  end

  # def create
  #   @plan = Plan.find(params[:plan_id])
  #   @plan_recipe = PlanRecipe.new(plan_recipe_params)
  #   @plan_recipe.plan_id = @plan.id
  #   if @plan_recipe.save
  #     redirect_to plan_path(@plan)
  #   else
  #     render :new, status: :unprocessable_entity
  #   end
  # end

  def edit
    @plan_recipe = plan_recipe.find(params[:id])
  end

  def update
    # @plan = Plan.find(params[:id])
    @plan_recipe = PlanRecipe.find(params[:id])
    @plan_recipe.recipe = Recipe.all.sample
    if @plan_recipe.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to show_recipes_path(@plan_recipe.plan) }
      end
    else
      render "plans/show", status: :unprocessable_entity
    end

    # @plan_recipe = plan_recipe.find(params[:id])
  end

  def destroy
    @plan_recipe = plan_recipe.find(params[:id])
    @plan_recipe.destroy
    redirect_to plan_path(@plan_recipe.plan), status: :see_other
  end

  def show_recipes
    @plan = Plan.find(params[:id])
  end

  private

  def plan_recipe_params
    params.require(:plan_recipe).permit(:recipe_id)
  end



end

app/views/plan_recipes/_details.html.erb
<%= turbo_frame_tag "plan_recipe_#{plan_recipe.id}" do %>
  <div class="show-recipes d-flex flex-row justify-content-between align-items-center">
    <div class="d-flex justify-content-between align-items-center px-5 mb-5 gap-5">
      <%= cl_image_tag plan_recipe.recipe.photo.key, width: 500, height: 500, crop: :fill, class: "border rounded-circle shadow" %>
      <div class="d-flex flex-column justify-content-evenly gap-5 w-75 me-5">
        <h1 class="m-0 text-center dark-green"><%= plan_recipe.recipe.name %></h1>
        <div class="green-border-button d-flex justify-content-evenly align-items-center text-center gap-4 mx-5" style="width:60vh">
          <p class="m-0"><i class="fa-solid fa-clock"></i> <%= plan_recipe.recipe.cook_time %></p>
          <p class="m-0"><i class="fa-solid fa-fire"></i> <%= plan_recipe.recipe.calories %></p>
          <p class="m-0"><i class="fa-solid fa-person"></i> <%= plan_recipe.recipe.servings %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="show-recipes d-flex flex-row justify-content-center align-items-center">
    <div class="d-flex flex-column justify-content-center align-items-center gap-5">
      <div class="d-flex justify-content-between gap-5 p-5">
        <div class="w-75">
          <h2 class="text-start my-0 pb-2 px-5 text-nowrap">How to Cook</h2>
          <div class="pt-2 mb-5 border-top-orange">
            <p class="d-inline-block m-0 p-1 px-5"><%= plan_recipe.recipe.instructions %></p>
          </div>
        </div>
        <div class="w-25">
          <h2 class="d-inline-block text-center my-0 pb-2 px-5 w-100">Ingredients</h2>
          <div class="pt-2 mb-5 border-top-orange d-flex flex-column justify-content-center">
            <% plan_recipe.recipe.recipe_ingredients.each do |ingredient|%>
              <p class="d-inline-block text-center mb-0 p-1 px-5"><%= ingredient.ingredient.name.capitalize %></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/plan_recipes/_form.html.erb
<%= simple_form_for [@plan, @plan_recipe] do |f| %>
  <%= f.association :recipe %>
  <%= f.button :submit %>
<% end %>

app/views/plan_recipes/_list.html.erb
<ul class="recipes-list m-0 p-0 position-fixed start-0 overflow-auto" id="aside" data-controller="recipes-list" data-preserve-scroll>
  <% @plan.plan_recipes.each do |plan_recipe| %>
    <%= link_to plan_plan_recipe_path(@plan, plan_recipe),
      id: "#{'highlight' if plan_recipe == selected_plan_recipe}",
      class: "m-2 p-2 d-flex justify-content-start align-items-center gap-3",
      data: { action: "click->recipes-list#highlight", recipes_list_target: "item" } do %>
        <%= cl_image_tag plan_recipe.recipe.photo.key, width: 70, height: 70, crop: :thumb, class: "border rounded-circle" %>
        <%= plan_recipe.recipe.name %>
    <% end %>
  <% end %>
</ul>

app/views/plan_recipes/_plan_recipe.html.erb
<%= turbo_frame_tag "plan_recipe_#{plan_recipe.id}" do %>
  <div class="d-flex flex-column justify-content-between border rounded-5 m-1 p-1 bg-info shadow" style="width: 14rem; height: 21rem; background-color: floral-white;">
    <div class="p-2 d-flex flex-column align-items-center">
      <%= cl_image_tag plan_recipe.recipe.photo.key, width: 90, height: 90, crop: :fill, class:"rounded-circle mb-2 shadow bg-body rounded border"%>
      <p class="text-center m-0"><small><strong><%= plan_recipe.recipe.name %></strong></small></p>
    </div>
    <div class="d-flex flex-column">
      <div class="d-flex justify-content-center">
        <%= button_to '<i class="refresh-button fa-solid fa-arrows-rotate"></i>'.html_safe,
                    plan_recipe_path(plan_recipe),
                    method: :patch,
                    data: { turbo_frame: "plan_recipe#{plan_recipe.id}"}, class:"refresh-button mb-2", style:"font-size: 24px" %>
      </div>
      <div class="p-2 border-top d-flex justify-content-between" style="height: 3rem;">
        <p><small><%= plan_recipe.recipe.calories %> kcal</small></p>
        <p><small><%= plan_recipe.recipe.cook_time %> min</small></p>
      </div>
    </div>
  </div>
<% end %>

app/views/plan_recipes/index.html.erb
<section class="overflow-y-scroll">
  <%= render 'plan_recipes/list', plan_recipes: @plan_recipes, selected_plan_recipe: @plan_recipe %>

  <div class="d-flex justify-content-end align-items-center",  style="margin: 0px auto; padding: 0">
    <%= render 'plans/download' %>
    <%= render 'shopping_lists/modal_shopping_list', shopping_list: @shopping_list %>
  </div>
  <%= render 'plan_recipes/details', plan_recipe: @plan_recipe %>

</section>

app/views/plan_recipes/new.html.erb
<div class="container m-3">
  <%= render "form" %>
</div>

app/views/plan_recipes/show.html.erb
<section class="overflow-y-scroll">
  <%= render 'plan_recipes/list', plan_recipes: @plan_recipes, selected_plan_recipe: @plan_recipe %>

    <div class="d-flex justify-content-end align-items-center", style="margin: 0px auto; padding: 0">
      <%= render 'plans/download', plan: @plan %>
      <%= render 'shopping_lists/modal_shopping_list', shopping_list: @shopping_list %>
    </div>
    <%= render 'plan_recipes/details', plan_recipe: @plan_recipe %>

</section>

app/views/plan_recipes/show_recipes.html.erb
<section>
  <div>
    <%# <h1><%= @plan.title.capitalize %></h1>
    <div class="d-flex justify-content-between mt-2 align-items-center">
    <h2 class="mb-0">Choose your recipes for your plan. You can refresh the ones you don't like!</h2>
      <%# <p class="pt-1 fs-24 mb-0">Choose your recipes for your plan. You can refresh the ones you don't like!</p> %>
      <p class="mb-0">
          <%= link_to 'Next',
                      calendar_path(shopping_list: true),
                      class: "green-bg-button", style:"font-size: 24px;"%>
      </p>
    </div>
  </div>


  <div class="d-flex justify-content-between mt-4 px-2 color-trans">
      <div class="text-center fw-bolder m-1 p-1 mb-0" style="width: 12rem;">
        <p class="mb-0">Mon</p>
      </div>
      <div class="text-center fw-bolder m-1 p-1 mb-0" style="width: 12rem;">
        <p class="mb-0">Tue</p>
      </div>
      <div class="text-center fw-bolder m-1 p-1 mb-0" style="width: 12rem;">
        <p class="mb-0">Wed</p>
      </div>
      <div class="text-center fw-bolder m-1 p-1 mb-0" style="width: 12rem;">
        <p class="mb-0">Thu</p>
      </div>
      <div class="text-center fw-bolder m-1 p-1 mb-0" style="width: 12rem;">
        <p class="mb-0">Fri</p>
      </div>
      <div class="text-center fw-bolder m-1 p-1 mb-0" style="width: 12rem;">
        <p class="mb-0">Sat</p>
      </div>
      <div class="text-center fw-bolder m-1 p-1 mb-0" style="width: 12rem;">
        <p class="mb-0">Sun</p>
      </div>
    </div>



  <div class="">
    <div class="row row-cols-7 g-3" id="plan_recipes">
      <% @plan.plan_recipes.order(:id).each do |plan_recipe| %>
        <div class="col col-custom-7 align-center">
          <%= render "plan_recipes/plan_recipe", plan_recipe: plan_recipe %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</section>

app/views/plan_recipes/update.turbo_stream.erb
<%= turbo_stream.update @plan_recipe %>