config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :plans do
    resources :plan_recipes, only: [:index, :show]

    member do
      patch :update_positions
    end
  end

  resources :plan_recipes, only: :update
  resources :recipes, only: :create
  resources :shopping_lists, only: [:create, :update, :edit]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # get "surveys", to: "surveys#new"
  # get "surveys", to: "surveys#create"
  # get "up" => "rails/health#show", as: :rails_health_check

  get "/plans/:id/calendar", to: "plans#edit_calendar", as: :calendar
  get "/plans/:id/recipes", to: "plan_recipes#show_recipes", as: :show_recipes
  get "plans/:id/recipes/edit", to: "plans#edit", as: :edit_recipe
  post "plans/:id/recipes/update", to: "plan_recipes#update", as: :update_recipe
  get "/plans/:id/shopping-list", to: "plans#show_shopping_list", as: :show_shopping_list
  # get "plans/:id/shopping-list/edit/:id", to: "shopping_lists#edit", as: :edit_shopping_list

  # Defines the root path route ("/")
  # root "posts#index"

  # resources :surveys, only: [] do
  #   collection do
  #     get :step_one
  #     match :step_two, via: [:get, :post]
  #     match :step_three, via: [:get, :post]
  #     match :step_four, via: [:get, :post]
  #     post :submit_survey
  #   end
  # end

  resources :surveys
end
       # get 'step/:step', to: 'surveys#step', as: :survey_step
       # post 'submit', to: 'surveys#submit_survey', as: :submit_survey
   # end
 # end
# end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <h2 class="m-0">PlatePal</h2>

  <div class="d-flex justify-content-between mb-3 footer-body">
    <div>
      <span class="d-inline-block">ADDRESS</span>
      <p>RUA DO CENTRO CULTURAL 45, 1700-006 LISBOA</p>
      <span class="d-inline-block">PHONE</span>
      <p>+351 926 142 424</p>
    </div>

    <div>
      <span class="d-inline-block">GENERAL ENQUIRIES</span>
      <p>HELLO@PLATEPAL.COM</p>
      <span class="d-inline-block">SUPPORT</span>
      <p>SUPPORT@PLATEPAL.COM</p>
    </div>

    <div>
      <span class="d-inline-block">Receive our latest news.</span>
      <form class="d-flex flex-row justify-content-between pb-1 footer-form">
        <input
          type="text"
          class="border-0 flex-grow-1"
          placeholder="Email Address"
          required
        />
        <button class="border-0">SUBSCRIBE <i class="fa-solid fa-arrow-right"></i></button>
      </form>
    </div>
  </div>

  <div class="d-flex justify-content-between align-items-center footer-bottom">
    <div class="d-flex justify-content-center gap-3">
      <i class="fa-brands fa-github-alt fa-lg"></i>
      <i class="fa-brands fa-facebook-f fa-lg"></i>
      <i class="fa-brands fa-linkedin-in fa-lg"></i>
      <i class="fa-brands fa-instagram fa-lg"></i>
    </div>
    <span class="d-block m-0">COPYRIGHT &copy 2024 PlatePal. ALL RIGHTS RESERVED.</span>
  </div>
</footer>

app/views/shared/_navbar.html.erb
 <nav class="d-flex justify-content-between align-items-center">
  <%= link_to root_path do %>
    <%= image_tag "image.jpg", alt: "PlatePal", width: "230px" %>
  <% end %>
  <div class="d-flex flex-row align-items-center">
    <%# <li class="me-3">Home</li> %>
    <%# <li class="mx-3">My Calendar</li>
    <li class="mx-3">Contacts</li>
    <li class="ms-3">About</li> %>
  </div>
  <div class="d-flex align-items-center">
    <%= link_to "Generate Plan", surveys_path, class:"orange-border-button me-3 text-decoration-none"%>
    <div class="dropdown">
      <% if user_signed_in? %>
        <button class="avatar navbar-toggle bg-warning" role="button" data-bs-toggle="dropdown" aria-expanded="false" >
          <i class="fa-solid fa-user text-white", style="font-size:24px"></i>
        </button>
        <ul class="dropdown-menu p-0">
          <li class="dropdown-item py-2 px-4"><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class:"text-green text-decoration-none"%></li>
        </ul>
      <% else %>
        <%= button_to '<i class="fa-solid fa-user text-white"></i>'.html_safe, new_user_session_path, class:"text-decoration-none avatar navbar-toggle bg-warning", style:"font-size:24px"%>
      <% end %>
    </div>
  </div>
</nav>