config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :plans do
    resources :plan_recipes, only: [:index, :show]

    member do
      patch :update_positions
    end
  end

  resources :plan_recipes, only: :update
  resources :recipes, only: :create
  resources :shopping_lists, only: [:create, :update, :edit]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # get "surveys", to: "surveys#new"
  # get "surveys", to: "surveys#create"
  # get "up" => "rails/health#show", as: :rails_health_check

  get "/plans/:id/calendar", to: "plans#edit_calendar", as: :calendar
  get "/plans/:id/recipes", to: "plan_recipes#show_recipes", as: :show_recipes
  get "plans/:id/recipes/edit", to: "plans#edit", as: :edit_recipe
  post "plans/:id/recipes/update", to: "plan_recipes#update", as: :update_recipe
  get "/plans/:id/shopping-list", to: "plans#show_shopping_list", as: :show_shopping_list
  # get "plans/:id/shopping-list/edit/:id", to: "shopping_lists#edit", as: :edit_shopping_list

  # Defines the root path route ("/")
  # root "posts#index"

  # resources :surveys, only: [] do
  #   collection do
  #     get :step_one
  #     match :step_two, via: [:get, :post]
  #     match :step_three, via: [:get, :post]
  #     match :step_four, via: [:get, :post]
  #     post :submit_survey
  #   end
  # end

  resources :surveys
end
       # get 'step/:step', to: 'surveys#step', as: :survey_step
       # post 'submit', to: 'surveys#submit_survey', as: :submit_survey
   # end
 # end
# end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  has_many :plan_recipes, dependent: :destroy
  has_many :recipes, through: :plan_recipes
  has_many :shopping_lists
  has_many :ingredients, through: :shopping_list

  validates :title, presence: true
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.where(user_id: current_user.id)
  end

  def show
    @plan = Plan.find(params[:id])
    @plan_recipes = @plan.plan_recipes.order(:position)
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.user = current_user
    @plan.start_date = Date.today
    @plan.end_date = Date.today + 7
    @recipes = query_recipes
    if @plan.save!
      14.times do
        @plan_recipe = PlanRecipe.new
        @plan_recipe.plan_id = @plan.id
        @plan_recipe.recipe_id = @recipes.all.sample.id
        @plan_recipe.save!
      end
      @plan.save!
      redirect_to show_recipes_path(@plan)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @plan = Plan.find(params[:id])
    @plan.plan_recipes
  end

  def update_plan_recipe
    @plan = Plan.find(params[:id])
    @plan.plan_recipes.recipe = Recipe.all.sample
  end

  def edit_calendar
    @plan = Plan.find(params[:id])
    @plan_recipes = @plan.plan_recipes.order(:position)
    assign_positions_if_needed
    generate_shopping_list(@plan) if params[:shopping_list] == "true"
  end

  def update_positions
    positions = params[:positions]
    positions.each do |id, position|
      plan_recipe = PlanRecipe.find(id)
      plan_recipe.update!(position: position)
    end

    render json: { success: true }
  rescue ActiveRecord::RecordInvalid => e
    render json: { success: false, error: e.message }, status: :unprocessable_entity
  end

  def show_shopping_list
    @plan = Plan.find(params[:id])
    #generate_shopping_list(@plan) if params[:shopping_list] == "true"
    @plan_recipes = @plan.plan_recipes
    @shopping_list = ShoppingList.where(plan: @plan).includes(:ingredient).order('ingredients.name')
  end

  private

  def plan_params
    params.require(:plan).permit(:title)
  end

  def plan_recipe_params
    params.require(:plan_recipe).permit(:recipe_id, :position)
  end

  def assign_positions_if_needed
    @plan.plan_recipes.each_with_index do |plan_recipe, index|
      if plan_recipe.position.nil?
        plan_recipe.update!(position: index + 1)
      end
    end
  end

  def generate_shopping_list(plan)
    plan.recipes.each do |recipe|
      recipe.recipe_ingredients.each do |recipe_ingredient|
        if ShoppingList.find_by(plan: plan, ingredient: recipe_ingredient.ingredient)
          shopping_list = ShoppingList.find_by(plan: plan, ingredient: recipe_ingredient.ingredient)
          shopping_list.update(quantity: shopping_list.quantity + recipe_ingredient.quantity)
        else
          ShoppingList.create(plan: plan, ingredient: recipe_ingredient.ingredient, unit:recipe_ingredient.unit, quantity: recipe_ingredient.quantity)
        end
      end
    end
  end

  def query_recipes
    @survey = Survey.where(user_id: current_user.id).last
    @recipes = Recipe.all
    if @survey.availability == "limited"
      @filtered_recipes = @recipes.where("cook_time <= ? AND servings = ?", 30, @survey.servings)
    else
      @filtered_recipes = @recipes.where('restrictions @> ARRAY[?]::varchar[] AND servings = ?', @survey.diet, @survey.servings)
    end
    @filtered_recipes
  end
end

app/views/plans/_calendar.html.erb
<div class="d-flex flex-column justify-content-between border rounded-5 m-1 p-1 bg-info shadow" style="width: 14rem; height: 21rem; background-color: floral-white;" draggable="true" data-id="<%= plan_recipe.id %>" >
  <div class="p-2 d-flex flex-column align-items-center">
    <%= cl_image_tag plan_recipe.recipe.photo.key, width: 90, height: 90, crop: :fill, class:"rounded-circle mb-2 shadow bg-body rounded border" %>
    <p class="text-center m-0"><small><strong><%= plan_recipe.recipe.name %></strong></small></p>
  </div>

  <div class="d-flex flex-column">
    <div class="d-flex justify-content-center mb-2">
      <i class="fa-solid fa-arrows-up-down-left-right text-center mt-2 refresh-button mb-2" style="font-size: 24px"></i>

    </div>

    <div class="p-2 border-top d-flex justify-content-between" style="height: 3rem;">
      <p><small><%= plan_recipe.recipe.calories %> kcal</small></p>
      <p><small><%= plan_recipe.recipe.cook_time %> min</small></p>
    </div>
  </div>
</div>

app/views/plans/_download.html.erb
<button type="button" class="fw-normal me-3 align-items-start rounded-circle bg-success" style="font-size: 22px; height:53px; width: 53px; " data-bs-toggle="modal" data-bs-target="#downloadBackdrop">
<i class="fa-solid fa-download text-white"></i>
</button>

<!-- Modal -->
<div class="modal fade" id="downloadBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-1" id="staticBackdropLabel"><%= @plan.title.capitalize %></h1>
        <button type="button" class="btn-close me-2" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>This plan has been sent to your email.</p>
        <br>
        <p>Happy cooking! <i class="fa-regular fa-face-smile-beam"></i></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-warning text-white" data-bs-dismiss="modal">Gotcha!</button>
      </div>
    </div>
  </div>
</div>

app/views/plans/_form.html.erb
<div class="w-50", data-turbo-frame="plan">
  <%= simple_form_for @plan do |f| %>
    <%= f.input :title %>
    <%= f.button :submit, class:"btn btn-warning my-3 text-white rounded-pill" %>
  <% end %>
</div>

app/views/plans/_recipes.html.erb
<%= turbo_frame_tag "plan_recipe_#{plan_recipe.id}" do %>
  <div class="card m-3" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title fs-2 text fw-bolder"><%= plan_recipe.recipe.name %></h5>
      <%= button_to "Change Recipe",
                plan_recipe_path(plan_recipe),
                method: :patch,
                data: { turbo_frame: "plan_recipe#{plan_recipe.id}" } %>
    </div>
  </div>
<% end %>

app/views/plans/_show_shopping_list.html.erb
<%= turbo_frame_tag :shopping_list do %>
  <div class="container">
    <div class="row g-3 py-2">
      <% @shopping_list.each_slice(3) do |row_items| %>
        <div class="d-flex justify-content-start w-100 mt-1 ps-0">
          <% row_items.each do |item| %>
            <div class="col-4 px-1 py-1 me-2">
              <%= turbo_frame_tag dom_id(item) do %>
                <div class="list-group-item d-flex justify-content-between align-items-center mb-0", style="max-width: 95%; width: 95%;">
                  <div>
                    <strong><%= item.ingredient.name %></strong>
                  </div>
                  <div class="d-flex align-items-center">
                    <%= form_with model: item, method: :patch, local: false, class: "d-inline-flex align-items-center" do |f| %>
                      <div class="input-group input-group-sm me-2">
                        <%= f.number_field :quantity, class: "form-control text-center", style: "width: 70px;", step: 1 %>
                        <span class="input-group-text bg-light text-muted justify-content-center", style= "width: 60px;">
                        <% if item.unit == "" %>
                          <%= "-" %>
                        <% else %>
                          <%= item.unit %>
                        <% end %>
                        </span>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/plans/copy_show.html.erb
<% @plan.recipes.each do |recipe| %>
  <%= cl_image_tag recipe.photo.key, crop: :fill, class: "border rounded w-100"  %>
  <%= recipe.name %>
  <%# <%= recipe.time %>
<% end %>

app/views/plans/edit_calendar.html.erb
<section>
  <div>
    <%# <h1><%= @plan.title.capitalize %></h1>
    <div class="d-flex justify-content-between mt-2 align-items-center">
      <h2 class="mb-0">Drag and drop meals to rearrange your schedule!</h2>
      <%# <p class="pt-3 fs-24">Choose your recipes for your plan. You can refresh the ones you don't like!</p> %>
      <p class="mb-0">
          <%= link_to 'Done',
                      plan_plan_recipes_path(@plan),
                      class: "green-bg-button", style:"font-size: 24px;"%>
      </p>
    </div>
  </div>


    <div class="d-flex justify-content-between mt-4 px-2">
      <div class="text-center fw-bolder m-1 p-1 mb-0" style="width: 12rem;">
        <p class="mb-0">Mon</p>
      </div>
      <div class="text-center fw-bolder m-1 p-1 mb-0" style="width: 12rem;">
        <p class="mb-0">Tue</p>
      </div>
      <div class="text-center fw-bolder m-1 p-1 mb-0" style="width: 12rem;">
        <p class="mb-0">Wed</p>
      </div>
      <div class="text-center fw-bolder m-1 p-1 mb-0" style="width: 12rem;">
        <p class="mb-0">Thu</p>
      </div>
      <div class="text-center fw-bolder m-1 p-1 mb-0" style="width: 12rem;">
        <p class="mb-0">Fri</p>
      </div>
      <div class="text-center fw-bolder m-1 p-1 mb-0" style="width: 12rem;">
        <p class="mb-0">Sat</p>
      </div>
      <div class="text-center fw-bolder m-1 p-1 mb-0" style="width: 12rem;">
        <p class="mb-0">Sun</p>
      </div>
    </div>


    <div class="">
      <div class="row row-cols-7 g-3" data-controller="drag-and-drop" data-drag-and-drop-update-positions-url="<%= update_positions_plan_path(@plan) %>">
        <% @plan.plan_recipes.order(:id).each do |plan_recipe| %>
          <div class="col col-custom-7 align-center">
            <%= render "plans/calendar", plan_recipe: plan_recipe %>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>
</section>

app/views/plans/new.html.erb
<div class="container m-3">
  <%= render "form" %>
</div>

app/views/plans/show.html.erb
<div class="container m-3">
  <div class="card-category">
    <h1><%= @plan.title %></h1>
  </div>

  <div class="m-3 d-flex justify-content-between">
    <div class="d-flex flex-wrap">
      <% @plan.plan_recipes.each do |plan_recipe| %>
        <div class="card border-rounded m-3" style="width: 18rem;">
          <div class="card-body">
            <%= cl_image_tag plan_recipe.recipe.photo.key, crop: :fill, class:"border w-25" %>
            <h5 class="card-title fs-2 text fw-bolder"><%= plan_recipe.recipe.name %></h5>
            <p class="card-title"><%= plan_recipe.recipe.ingredients_list %></p>
            <p class="card-title"><%= plan_recipe.recipe.instructions %> ✦</p>
            <p class="card-title"><%= plan_recipe.recipe.cook_time %></p>
            <p class="card-title"><%= plan_recipe.recipe.servings %></p>
            <%= link_to "SWITCH", new_plan_plan_recipe_path(@plan), class:"btn btn-danger text-white" %>
          </div>
        </div>
      <% end %>
      </div>
  </div>
</div>

app/views/plans/update.turbo_stream.erb
<%= turbo_stream.update @pshopping_list %>